analysis:
  model: "mistral"
  temperature: 0
  format: "json"
  num_ctx: 8192
  base_url: "http://localhost:8080"
embedding:
  model: "nomic-embed-text"
  base_url: "http://localhost:8080"
mutation:
  model: "llama3"
  temperature: 1
  format: "json"


